spring:
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&userSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: tuyx
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"