spring:
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: tuyx
    password: 123456
  flyway:
    locations: classpath:/db
    baseline-on-migrate: false