server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: tuyx
    password: 123456
    virtual-host: znjf-host
#    listener:
#      simple:
#        concurrency: 1
#        acknowledge-mode: auto